package application;

import java.io.File;
import java.io.IOException;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class BillManagement extends Application {
	public static String BASE_FOLDER = "Electricity Bill Management";

	@Override
	public void start(Stage primaryStage) throws Exception {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("./views/MainApplication.fxml"));
			StackPane pane = loader.load();
			
			Scene scene = new Scene(pane);
			scene.getStylesheets().add("/application/resources/styles.css");
			pane.getStyleClass().add("header");
			
			primaryStage.setScene(scene);
			primaryStage.setTitle("CITE ELECTRICITY BILL MANAGEMENT (CEBM)");
			primaryStage.centerOnScreen();
			primaryStage.setMinHeight(500);
			primaryStage.setMinWidth(750);
			primaryStage.setHeight(500);
			primaryStage.setWidth(750);
			primaryStage.getIcons().add(new Image(getClass().getResource("/resources/logo.png").toString()));
			primaryStage.show();
		}catch(IOException ex) {
			ex.printStackTrace();
			System.exit(0);
		}

	}
	
	public static void main(String[] args) {
		launch(args);
	}
	
	public static String getSavePath(String filename) {
		//Returns the common base path for saving all files generated by the application
		String root = System.getProperty("user.home")+"/"+BASE_FOLDER+"/Files";
		File file = new File(root);
		if(!file.exists()) {
			file.mkdir();
		}
		return root.concat("/").concat(filename);
	}
}
